### ISSUE TITLE
macOS build is failing on Catalina

### ISSUE THREAD

**Issue by deepakgangwar** [avast/retdec-r2plugin#15] opened 2020-05-21 15:28 UTC
I tried building this plugin for cutter and the build failed with following error (same error occurred while installing through r2pm)

> Scanning dependencies of target retdec-getsig
[ 44%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/image.cpp.o
[ 44%] Building CXX object src/getsig/CMakeFiles/retdec-getsig.dir/getsig.cpp.o
[ 44%] Building CXX object src/llvmir2hll/CMakeFiles/retdec-llvmir2hll.dir/ir/continue_stmt.cpp.o
[ 44%] Building CXX object src/cpdetect/CMakeFiles/retdec-cpdetect.dir/compiler_detector/heuristics/heuristics.cpp.o
[ 44%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/coff/coff_image.cpp.o
[ 44%] Linking CXX executable retdec-getsig
[ 45%] Building CXX object src/llvmir2hll/CMakeFiles/retdec-llvmir2hll.dir/ir/deref_op_expr.cpp.o
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [src/getsig/retdec-getsig] Error 1
make[4]: *** [src/getsig/CMakeFiles/retdec-getsig.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....

macOS version: 10.15.4

**Comment by xkubov** [comment] 2020-05-30 16:03
Hi, could you please send the whole log of the build?

**Comment by xkubov** [comment] 2020-08-02 13:49
I am closing this issue as I am unable to reproduce this issue. Plugin tested with macOS 10.15.5.

**Closed by xkubov** 2020-08-02 13:49 UTC
Labels: P-build
